baseurl = "http://jamesreuss.co.uk/"
languageCode = "en-us"
title = "James Reuss"
theme = "timeline"
canonifyurls = true

[params]
  author = "James Reuss"
  description = "Wouldn't it be great to talk to your house?"
  disqusShortname = "jamesreuss"
  googleAnalytics = "UA-36805184-1"
